export function mkBrief({ source, content, mediaUrl, fetchError, suggestedTitle, title }) {
  const text = (content || '').trim();
  const lines = [];
  lines.push(`# Bug brief`);
  lines.push('');
  if (source) lines.push(`Source: ${source}`);
  if (mediaUrl) lines.push(`Video: ${mediaUrl}`);
  if (fetchError) lines.push(`Fetch: failed (${fetchError}) — paste transcript/notes via \`fathom2action --stdin\``);
  lines.push('');
  lines.push('## Suggested issue title (optional)');
  lines.push('');
  const bestTitle = suggestedTitle || title || '';
  lines.push(`- ${bestTitle ? bestTitle : ''}`);
  lines.push('');
  lines.push('## Summary (1 sentence)');
  lines.push('');
  lines.push('- ');
  lines.push('');
  lines.push('## Repro steps');
  lines.push('');
  lines.push('1. ');
  lines.push('');
  lines.push('## Expected vs actual');
  lines.push('');
  lines.push('- Expected: ');
  lines.push('- Actual: ');
  lines.push('');
  lines.push('## Context / environment');
  lines.push('');
  lines.push('- Where (env/feature flag/build): ');
  lines.push('- Who saw it: ');
  lines.push('- When: ');
  lines.push('');
  lines.push('## Timestamps (if mentioned)');
  lines.push('');
  lines.push('- ');
  lines.push('');
  lines.push('## Notes / raw extract');
  lines.push('');
  lines.push('```');
  lines.push(text.slice(0, 4000));
  if (text.length > 4000) lines.push('\n…(truncated)…');
  lines.push('```');
  lines.push('');
  lines.push('## Next actions');
  lines.push('');
  lines.push('- [ ] Create Linear/GitHub issue');
  lines.push('- [ ] Assign owner');
  lines.push('- [ ] Add severity + scope');
  return lines.join('\n');
}
